FROM ubuntu:15.04

#ENV DEBIAN_FRONTEND noninteractive 

RUN apt-get update
RUN apt-get install -y x11-apps
RUN adduser me
#RUN apt-get install -y libqt5... ?????????
#RUN apt-get install -y libmagickcore-6.q16-2
# or (more than needed?)
# RUN apt-get install -y magickcore
#RUN apt-get install -y xinit ????????
